# Generated by Django 3.0.3 on 2020-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=10)),
                ('bids', models.TextField()),
                ('asks', models.TextField()),
                ('closeoutBid', models.FloatField(default=0.0)),
                ('closeoutAsk', models.FloatField(default=0.0)),
                ('tradeable', models.BooleanField(default=False)),
                ('time', models.DateField()),
            ],
        ),
    ]
