# Generated by Django 3.0.3 on 2020-02-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
    ]
