# Generated by Django 3.0.3 on 2020-02-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0003_auto_20200213_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='closeoutAsk',
            new_name='closeout_ask',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='closeoutBid',
            new_name='closeout_bid',
        ),
    ]
