# Generated by Django 3.0.3 on 2020-03-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0006_candle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
